
$(document).ready(function(){
    $('input[type="radio"]').click(function(){
        if($(this).attr("value")=="newborn"){
            $(".age-info").not(".newborn").hide();
            $(".newborn").show();
            $("#newborn-button").click(function(){
                $("#newborn-next").show();
                $("#newborn-descrip").hide();
              });
            $("#newborn-back-button").click(function(){
              $("#newborn-descrip").show();
              $("#newborn-next").hide();
            });
        }
        if($(this).attr("value")=="twoweeks"){
            $(".age-info").not(".two-weeks").hide();
            $(".two-weeks").show();
            $("#two-weeks-button").click(function(){
                $("#two-weeks-next").show();
                $("#two-weeks-descrip").hide();
              });
              $("#two-weeks-back-button").click(function(){
                $("#two-weeks-descrip").show();
                $("#two-weeks-next").hide();
              });
        }
        if($(this).attr("value")=="threefourweeks"){
            $(".age-info").not(".threefour-weeks").hide();
            $(".threefour-weeks").show();
            $("#threefour-weeks-button").click(function(){
                $("#threefour-weeks-next").show();
                $("#threefour-weeks-descrip").hide();
              });
              $("#threefour-weeks-back-button").click(function(){
                $("#threefour-weeks-descrip").show();
                $("#threefour-weeks-next").hide();
              });
        }
        if($(this).attr("value")=="fivesixweeks"){
            $(".age-info").not(".fivesix-weeks").hide();
            $(".fivesix-weeks").show();
            $("#fivesix-weeks-button").click(function(){
                $("#fivesix-weeks-next").show();
                $("#fivesix-weeks-descrip").hide();
              });
              $("#fivesix-weeks-back-button").click(function(){
                $("#fivesix-weeks-descrip").show();
                $("#fivesix-weeks-next").hide();
              });
        }
        if($(this).attr("value")=="seveneightweeks"){
            $(".age-info").not(".seveneight-weeks").hide();
            $(".seveneight-weeks").show();
            $("#seveneight-weeks-button").click(function(){
                $("#seveneight-weeks-next").show();
                $("#seveneight-weeks-descrip").hide();
              });
              $("#seveneight-weeks-back-button").click(function(){
                $("#seveneight-weeks-descrip").show();
                $("#seveneight-weeks-next").hide();
              });
        }
        if($(this).attr("value")=="tentwelveweeks"){
            $(".age-info").not(".tentwelve-weeks").hide();
            $(".tentwelve-weeks").show();
            $("#tentwelve-weeks-button").click(function(){
                $("#tentwelve-weeks-next").show();
                $("#tentwelve-weeks-descrip").hide();
              });
              $("#tentwelve-weeks-back-button").click(function(){
                $("#tentwelve-weeks-descrip").show();
                $("#tentwelve-weeks-next").hide();
              });
        }
        if($(this).attr("value")=="threefourmonths"){
            $(".age-info").not(".threefour-months").hide();
            $(".threefour-months").show();
            $("#threefour-months-button").click(function(){
                $("#threefour-months-next").show();
                $("#threefour-months-descrip").hide();
              });
              $("#threefour-months-back-button").click(function(){
                $("#threefour-months-descrip").show();
                $("#threefour-months-next").hide();
              });
        }
    });

});
